services:
#
#  frontend:
#    build:
#      context: frontend
#      dockerfile: Dockerfile
#    container_name: frontend
#    volumes:
#      - ./frontend/src:/app/src

  postgres:
    image: postgres
    env_file:
      - ./.env
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]



  redis:
    image: redis/redis-stack:latest
    ports:
       - "8001:8001"
       - "6379:6379"
    container_name: redis
    volumes:
      - redis_volume:/data
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8002:80"
    container_name: pgadmin4
    volumes:
      - pgadmin_volume:/var/lib/pgadmin
    
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@example.com
      - PGADMIN_DEFAULT_PASSWORD=12345

    depends_on:
      - postgres


  backend:
    build:
      context: ./backend
      dockerfile: ./web.Dockerfile
    volumes:
      - ./backend/src/web:/src/web
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: postgres
      REDIS_HOST: redis

    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy

    container_name: backend
    expose:
      - 80




  nginx:
   container_name: nginx
   image: nginx:latest
   ports:
     - "80:80"
   volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./nginx/cors.conf:/etc/nginx/cors.conf
     - ./backend/src/web/app/static:/www/data
   depends_on:
     - backend
    #  - frontend



volumes:
  redis_volume: {}
  pgdata: {}
  pgadmin_volume: