"""seed bids

Revision ID: 72dd14e611d3
Revises: d35e560dba53
Create Date: 2024-11-08 11:00:20.001372

"""
from datetime import datetime
from typing import Sequence, Union

import pandas as pd
from alembic import op
import sqlalchemy as sa

from sqlalchemy.ext.asyncio import AsyncSession, AsyncConnection

# revision identifiers, used by Alembic.
revision: str = '72dd14e611d3'
down_revision: Union[str, None] = 'd35e560dba53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bid_statuses',
    sa.Column('name', sa.String(length=90), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bids',
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('computer_tech_type', sa.String(length=80), nullable=False),
    sa.Column('computer_tech_model', sa.String(length=500), nullable=False),
    sa.Column('issuer_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['issuer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bid_masters',
    sa.Column('bid_id', sa.Integer(), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bid_id'], ['bids.id'], ),
    sa.ForeignKeyConstraint(['master_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spares',
    sa.Column('bid_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('count', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bid_id'], ['bids.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
    async def seed_db(connection: AsyncConnection):
        session = AsyncSession(bind=connection)
        df = pd.read_excel(r"C:\Users\zao\PycharmProjects\migrations\seed\inputDataRequests.xlsx")
        df['startDate'].apply(lambda x: datetime.strptime(x, '%Y-%d-%m'))




        op.run_async(seed_db)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spares')
    op.drop_table('bid_masters')
    op.drop_table('bids')
    op.drop_table('bid_statuses')
    # ### end Alembic commands ###
