"""empty message

Revision ID: 3d3fb90f23d6
Revises: 73320ebf6b81
Create Date: 2024-11-21 18:37:55.691747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.ext.asyncio import AsyncSession, AsyncConnection
from polyfactory.factories.sqlalchemy_factory import SQLAlchemyFactory

#class Factory(SQLAlchemyFactory):
#    __model__ =
#    __set_relationships__ = True


# revision identifiers, used by Alembic.
revision: str = '3d3fb90f23d6'
down_revision: Union[str, None] = '73320ebf6b81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sessions_user_id_fkey', 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_files_user_id_fkey', 'user_files', type_='foreignkey')
    op.drop_constraint('user_files_file_id_fkey', 'user_files', type_='foreignkey')
    op.create_foreign_key(None, 'user_files', 'files', ['file_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_files', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_roles_role_id_fkey', 'user_roles', type_='foreignkey')
    op.drop_constraint('user_roles_user_id_fkey', 'user_roles', type_='foreignkey')
    op.create_foreign_key(None, 'user_roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_roles', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
    async def seed_db(connection: AsyncConnection):
        session = AsyncSession(bind=connection)
#        Factory.__async_session__ = session
#        await Factory.create_batch_async(10)


    op.run_async(seed_db)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.create_foreign_key('user_roles_user_id_fkey', 'user_roles', 'users', ['user_id'], ['id'])
    op.create_foreign_key('user_roles_role_id_fkey', 'user_roles', 'roles', ['role_id'], ['id'])
    op.drop_constraint(None, 'user_files', type_='foreignkey')
    op.drop_constraint(None, 'user_files', type_='foreignkey')
    op.create_foreign_key('user_files_file_id_fkey', 'user_files', 'files', ['file_id'], ['id'])
    op.create_foreign_key('user_files_user_id_fkey', 'user_files', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key('sessions_user_id_fkey', 'sessions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
