"""empty message

Revision ID: 77f477c3c4b7
Revises: 3d3fb90f23d6
Create Date: 2024-11-22 07:02:00.703007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.ext.asyncio import AsyncSession, AsyncConnection
from polyfactory.factories.sqlalchemy_factory import SQLAlchemyFactory
from storage.db.models import User
#class Factory(SQLAlchemyFactory):
#    __model__ =
#    __set_relationships__ = True


# revision identifiers, used by Alembic.
revision: str = '77f477c3c4b7'
down_revision: Union[str, None] = '3d3fb90f23d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
    async def seed_db(connection: AsyncConnection):
        session = AsyncSession(bind=connection)
        u = User(phone='21', login='admin', password='string', first_name='1', middle_name='1', last_name='1', is_superuser=True,
             is_active=True, is_verified=True)
        session.add(u)
        await session.commit()

#        Factory.__async_session__ = session
#        await Factory.create_batch_async(10)


    op.run_async(seed_db)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
